Name: Aumkar Gadekar <br>
Roll No: 21 <br>
UID: 2017130023 <br>

# Exp 6: Fuzzy Sets and Fuzzy Relations

### Aim : To implement Fuzzy Sets and Fuzzy Relations

In [1]:
import numpy as np

### Operations on fuzzy sets

#### Generating data

In [14]:
membership1=np.random.rand(5)
membership2=np.random.rand(5)

members=['a','b','c','d','e']
s1 = dict(zip(members, membership1)) 
s2 = dict(zip(members, membership2)) 
print(s1)
print(s2)

{'a': 0.8996761942822264, 'b': 0.1477007963599527, 'c': 0.9237136367464366, 'd': 0.3323894664998439, 'e': 0.9423081565267528}
{'a': 0.1763402667461309, 'b': 0.9096751523168559, 'c': 0.3665132283539606, 'd': 0.8515511837753403, 'e': 0.22965547188727997}


#### Union

In [17]:
def union(s1,s2):
    union=dict()
    for i in s1:
        union[i]=max(s1[i],s2[i])
    return union

In [18]:
union(s1,s2)

{'a': 0.8996761942822264,
 'b': 0.9096751523168559,
 'c': 0.9237136367464366,
 'd': 0.8515511837753403,
 'e': 0.9423081565267528}

#### Intersection

In [19]:
def intersection(s1,s2):
    intersection=dict()
    for i in s1:
        intersection[i]=min(s1[i],s2[i])
    return intersection

In [20]:
intersection(s1,s2)

{'a': 0.1763402667461309,
 'b': 0.1477007963599527,
 'c': 0.3665132283539606,
 'd': 0.3323894664998439,
 'e': 0.22965547188727997}

#### Complement

In [21]:
def complement(s1):
    complement=dict()
    for i in s1:
        complement[i]=1-s1[i]
    return complement

In [22]:
complement(s1)

{'a': 0.10032380571777355,
 'b': 0.8522992036400473,
 'c': 0.07628636325356342,
 'd': 0.6676105335001561,
 'e': 0.057691843473247184}

#### Difference

In [25]:
def difference(s1,s2):
    diff=dict()
    c=complement(s2)
    for i in s1:
        diff[i]=min(s1[i],c[i])
    return diff

In [26]:
difference(s1,s2)

{'a': 0.8236597332538691,
 'b': 0.09032484768314408,
 'c': 0.6334867716460394,
 'd': 0.14844881622465966,
 'e': 0.77034452811272}

In [27]:
difference(s2,s1)

{'a': 0.10032380571777355,
 'b': 0.8522992036400473,
 'c': 0.07628636325356342,
 'd': 0.6676105335001561,
 'e': 0.057691843473247184}

#### Cartesian product

In [50]:
def cartesian(s1,s2):
    cart=np.zeros((5,5))
    k1=list(s1.keys())
    k2=list(s2.keys())
    for i in range(len(s1)):
        for j in range(len(s2)):
            cart[i,j]=min(s1[k1[i]],s2[k2[j]])
    return cart

In [51]:
np.array(cartesian(s1,s2))

array([[0.17634027, 0.89967619, 0.36651323, 0.85155118, 0.22965547],
       [0.1477008 , 0.1477008 , 0.1477008 , 0.1477008 , 0.1477008 ],
       [0.17634027, 0.90967515, 0.36651323, 0.85155118, 0.22965547],
       [0.17634027, 0.33238947, 0.33238947, 0.33238947, 0.22965547],
       [0.17634027, 0.90967515, 0.36651323, 0.85155118, 0.22965547]])

### Operations on fuzzy relations

#### Generating data

In [63]:
r1 = np.random.rand(4,5)
r2 = np.random.rand(5,4)
print("r1: ", r1)
print("r2: ", r2)

r1:  [[0.19902997 0.11516313 0.708757   0.0263181  0.21484903]
 [0.86315236 0.68601418 0.370065   0.92664925 0.07100615]
 [0.03050529 0.14634883 0.68615107 0.07817835 0.33375369]
 [0.62621268 0.30525483 0.81067289 0.81070508 0.12277594]]
r2:  [[0.18340702 0.19787972 0.43245863 0.59599088]
 [0.3039868  0.49108931 0.64270064 0.58107577]
 [0.87763895 0.11350131 0.86549691 0.47192411]
 [0.43985492 0.97329782 0.94092709 0.75535336]
 [0.4326582  0.77463646 0.46212274 0.79443611]]


#### Max-min composition

In [68]:
def maxMinComp(r1,r2):
    t = []
    for i in range(len(r1)):
        temp = []
        for k in range(len(r2[0])):
            mx = []
            for j in range(len(r1[0])):
                mx.append(min(r1[i][j],r2[j][k]))
            m = max(mx)
            temp.append(m)
    t.append(temp)
    return t

In [69]:
np.array(maxMinComp(r1, r2))

array([[0.81067289, 0.81070508, 0.81070508, 0.75535336]])

#### Max product Composition

In [70]:
def maxProdComp(r1, r2):
    t = []
    for i in range(len(r1)):
        temp = []
        for k in range(len(r2[0])):
            max_prod = []
            for j in range(len(r1[0])):
                max_prod.append(r1[i][j]*r2[j][k])
            m = max(max_prod)
            temp.append(m)
        t.append(temp)
    return t  

In [71]:
np.array(maxProdComp(r1, r2))

array([[0.62203275, 0.16642989, 0.613427  , 0.33447952],
       [0.40759124, 0.9019057 , 0.87190939, 0.69994763],
       [0.6021929 , 0.25853778, 0.59386163, 0.32381124],
       [0.7114781 , 0.78905749, 0.76281438, 0.61236881]])

### Conclusion:

#### Fuzzy operations were understoond and implemented on Fuzzy sets as well as relations.

* Operations implemented on Fuzzy Sets: Union, Intersection, Complement, Cartesian product, Difference

* Operations implemented on Fuzzy Relations: Max min compostion, Max product compostion